PRAGMA foreign_keys = ON;
ALTER TABLE products ADD COLUMN short_name TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN landing_collection TEXT NOT NULL DEFAULT 'story' CHECK(landing_collection IN ('story','emotion','dedicated'));
ALTER TABLE products ADD COLUMN landing_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN storefront_state TEXT NOT NULL DEFAULT 'coming_soon' CHECK(storefront_state IN ('available','coming_soon','out_of_stock'));
ALTER TABLE products ADD COLUMN is_featured INTEGER NOT NULL DEFAULT 0 CHECK(is_featured IN (0,1));
ALTER TABLE products ADD COLUMN preorder_enabled INTEGER NOT NULL DEFAULT 0 CHECK(preorder_enabled IN (0,1));
ALTER TABLE products ADD COLUMN release_note TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN details_json TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(details_json));
CREATE TABLE product_interest (
 id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), email TEXT NOT NULL,
 kind TEXT NOT NULL CHECK(kind IN ('notify','preorder')), status TEXT NOT NULL DEFAULT 'new' CHECK(status IN ('new','contacted','closed')),
 created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
 UNIQUE(product_id,email,kind)
);
CREATE INDEX product_interest_status_idx ON product_interest(status,created_at);

-- One-time editorial import. Existing administrator edits (version > 1) win.
UPDATE products SET short_name='Harry Potter', landing_collection='story', landing_order=0, storefront_state='available', is_featured=1, details_json='["Dimensiuni aprox.: 6,5 × 5 × 4 cm","Înălțime cu capacul deschis: aprox. 6,2 cm","Funcționare: mecanică, prin rotirea manuală a manivelei","Obiect decorativ / de colecție 14+; nu este jucărie"]',
name=CASE WHEN version=1 THEN 'Cutiuță Muzicală Harry Potter cu Manivelă – Cadou de Colecție 14+' ELSE name END, tagline=CASE WHEN version=1 THEN 'Un mic obiect de colecție pentru cei care vor să păstreze puțină magie aproape.' ELSE tagline END, description=CASE WHEN version=1 THEN 'Cutiuța muzicală inspirată din universul Harry Potter combină lemnul închis la culoare, detaliile tematice și mecanismul metalic vizibil într-un obiect compact și memorabil. Ridici capacul, descoperi grafica interioară, apoi rotești ușor manivela pentru a pune mecanismul muzical în mișcare — fără baterii și fără încărcare. Redă o parte din piesa legendară a seriei de filme, creând o atmosferă magică și fidelă, care trezește emoții unice fanilor și colecționarilor.' ELSE description END, story=CASE WHEN version=1 THEN 'Este potrivită pentru fani, colecționari, adolescenți 14+, cadouri de aniversare, Crăciun, Secret Santa, dar și ca decor pentru birou, bibliotecă, raft sau vitrină. Mică la dimensiuni. Mare la capitolul magie. Imaginile sunt orientative și pot include elemente decorative care nu fac parte din produs.' ELSE story END WHERE slug='hp-keeper';
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_hp-keeper_0',id,'image','/produse/hp-keeper/card.webp','Cutiuță Muzicală Harry Potter cu Manivelă – Cadou de Colecție 14+','image/webp','Cutiuță Muzicală Harry Potter cu Manivelă – Cadou de Colecție 14+','product','active','cleared',1,1,-100,0 FROM products WHERE slug='hp-keeper' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_hp-keeper_1',id,'image','/produse/hp-keeper/1.webp','Cutiuța la lumina lumânării','image/webp','Cutiuța la lumina lumânării','product','active','cleared',1,1,-99,0 FROM products WHERE slug='hp-keeper' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_hp-keeper_2',id,'image','/produse/hp-keeper/2.webp','Capacul cu Hogwarts în fundal','image/webp','Capacul cu Hogwarts în fundal','product','active','cleared',1,1,-98,0 FROM products WHERE slug='hp-keeper' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_hp-keeper_3',id,'image','/produse/hp-keeper/3.webp','Dimensiuni și mecanism','image/webp','Dimensiuni și mecanism','product','active','cleared',1,1,-97,0 FROM products WHERE slug='hp-keeper' AND version=1;

-- One-time editorial import. Existing administrator edits (version > 1) win.
UPDATE products SET short_name='Game of Thrones', landing_collection='story', landing_order=1, storefront_state='available', is_featured=0, details_json='["Dimensiuni aprox.: 6,5 × 4 × 5 cm / 2.55 × 1.57 × 1.96 in","Funcționare: mecanică, prin rotirea manivelei","Obiect decorativ / de colecție 14+; nu este jucărie"]',
name=CASE WHEN version=1 THEN 'Cutiuță Muzicală Game of Thrones „Winter Is Coming” cu Manivelă – Cadou de Colecție 14+' ELSE name END, tagline=CASE WHEN version=1 THEN 'Iarna vine… dar de data aceasta aduce și muzică.' ELSE tagline END, description=CASE WHEN version=1 THEN 'O cutiuță muzicală cu atmosferă medieval-fantasy, creată pentru fanii Game of Thrones, colecționari și cei care caută un cadou mic, dar memorabil. Designul negru cu lupul direwolf, mesajul „Winter Is Coming” și mecanismul metalic vizibil îi oferă un aspect aparte, potrivit atât pentru colecție, cât și pentru decor.' ELSE description END, story=CASE WHEN version=1 THEN 'Rotește ușor manivela metalică, iar mecanismul clasic pune melodia în mișcare — manual, fără baterii și fără încărcare. Poate fi oferită la aniversări, Crăciun, Secret Santa sau altor pasionați de universuri fantasy și poate completa perfect un birou, o bibliotecă, un raft sau o vitrină de colecție. Mică la dimensiuni. Legendară prin atmosferă. Imaginile sunt orientative și pot include elemente de decor care nu fac parte din produs.' ELSE story END WHERE slug='got-winter';
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_got-winter_0',id,'image','/produse/got-winter/card.webp','Cutiuță Muzicală Game of Thrones „Winter Is Coming” cu Manivelă – Cadou de Colecție 14+','image/webp','Cutiuță Muzicală Game of Thrones „Winter Is Coming” cu Manivelă – Cadou de Colecție 14+','product','active','cleared',1,1,-100,0 FROM products WHERE slug='got-winter' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_got-winter_1',id,'image','/produse/got-winter/1.webp','Iarna începe cu magie','image/webp','Iarna începe cu magie','product','active','cleared',1,1,-99,0 FROM products WHERE slug='got-winter' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_got-winter_2',id,'image','/produse/got-winter/2.webp','Un dar cu poveste','image/webp','Un dar cu poveste','product','active','cleared',1,1,-98,0 FROM products WHERE slug='got-winter' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_got-winter_3',id,'image','/produse/got-winter/3.webp','Capacul „Winter Is Coming”','image/webp','Capacul „Winter Is Coming”','product','active','cleared',1,1,-97,0 FROM products WHERE slug='got-winter' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_got-winter_4',id,'image','/produse/got-winter/4.webp','Dimensiuni compacte','image/webp','Dimensiuni compacte','product','active','cleared',1,1,-96,0 FROM products WHERE slug='got-winter' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_got-winter_5',id,'image','/produse/got-winter/5.webp','Pieptene, cilindru și manivelă','image/webp','Pieptene, cilindru și manivelă','product','active','cleared',1,1,-95,0 FROM products WHERE slug='got-winter' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_got-winter_6',id,'image','/produse/got-winter/6.webp','Pentru seri cu farmec','image/webp','Pentru seri cu farmec','product','active','cleared',1,1,-94,0 FROM products WHERE slug='got-winter' AND version=1;

-- One-time editorial import. Existing administrator edits (version > 1) win.
UPDATE products SET short_name='Pisicuță și Lună', landing_collection='dedicated', landing_order=2, storefront_state='available', is_featured=0, details_json='["Dimensiuni aprox.: 6,4 × 3,6 × 5 cm","Funcționare: mecanică, prin rotirea manuală a manivelei","Lemn deschis la culoare, cu modele gravate","Obiect decorativ / de colecție 14+; nu este jucărie"]',
name=CASE WHEN version=1 THEN 'Cutiuță Muzicală cu Pisicuță și Lună – Manivelă, Cadou de Colecție 14+' ELSE name END, tagline=CASE WHEN version=1 THEN 'O cutiuță mică, o scenă de poveste și o melodie care face momentul mai cald.' ELSE tagline END, description=CASE WHEN version=1 THEN 'Cutiuța muzicală cu pisicuță, lună strălucitoare și fluturi este un obiect decorativ și de colecție cu un farmec aparte. Ridici capacul, descoperi ilustrația, apoi rotești ușor manivela pentru a pune în mișcare mecanismul muzical metalic — fără baterii și fără încărcare.' ELSE description END, story=CASE WHEN version=1 THEN 'Realizată din lemn deschis la culoare, cu modele decorative gravate și mecanism vizibil, este potrivită pentru iubitorii de pisici, colecționari, familie, cupluri sau persoane dragi. Poate fi oferită la aniversări, zile de naștere, Crăciun sau pur și simplu ca un mic dar-surpriză și poate fi păstrată ca decor pe birou, raft, bibliotecă ori într-o vitrină. Un dar mic, pentru bucurii mari. Imaginile sunt orientative și pot include elemente decorative care nu fac parte din produs.' ELSE story END WHERE slug='kitten';
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_kitten_0',id,'image','/produse/kitten/card.webp','Cutiuță Muzicală cu Pisicuță și Lună – Manivelă, Cadou de Colecție 14+','image/webp','Cutiuță Muzicală cu Pisicuță și Lună – Manivelă, Cadou de Colecție 14+','product','active','cleared',1,1,-100,0 FROM products WHERE slug='kitten' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_kitten_1',id,'image','/produse/kitten/1.webp','Pisicuța și luna, la lumina caldă','image/webp','Pisicuța și luna, la lumina caldă','product','active','cleared',1,1,-99,0 FROM products WHERE slug='kitten' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_kitten_2',id,'image','/produse/kitten/2.webp','Ambalajul pentru cadou','image/webp','Ambalajul pentru cadou','product','active','cleared',1,1,-98,0 FROM products WHERE slug='kitten' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_kitten_3',id,'image','/produse/kitten/3.webp','Cutiuța închisă, cu decor gravat','image/webp','Cutiuța închisă, cu decor gravat','product','active','cleared',1,1,-97,0 FROM products WHERE slug='kitten' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_kitten_4',id,'image','/produse/kitten/4.webp','Dimensiuni produs','image/webp','Dimensiuni produs','product','active','cleared',1,1,-96,0 FROM products WHERE slug='kitten' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_kitten_5',id,'image','/produse/kitten/5.webp','Farmec clasic, fără baterii','image/webp','Farmec clasic, fără baterii','product','active','cleared',1,1,-95,0 FROM products WHERE slug='kitten' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_kitten_6',id,'image','/produse/kitten/6.webp','Un dar plin de tandrețe','image/webp','Un dar plin de tandrețe','product','active','cleared',1,1,-94,0 FROM products WHERE slug='kitten' AND version=1;

-- One-time editorial import. Existing administrator edits (version > 1) win.
UPDATE products SET short_name='Halloween', landing_collection='dedicated', landing_order=3, storefront_state='available', is_featured=0, details_json='["Dimensiuni: 6,4 × 3,8 × 5 cm / 2.51 × 1.49 × 1.96 in","Funcționare: mecanică, prin rotirea manivelei, fără baterii","Design tematic Halloween cu mecanism vizibil","Recomandat 12+"]',
name=CASE WHEN version=1 THEN 'Cutiuță Muzicală Halloween cu Manivelă – Cadou Misterios & Decor Tematic' ELSE name END, tagline=CASE WHEN version=1 THEN 'O cutiuță mică, o melodie misterioasă și puțină magie de Halloween.' ELSE tagline END, description=CASE WHEN version=1 THEN 'Ridică capacul, rotește manivela și lasă mecanismul muzical să dea viață atmosferei. Designul tematic, detaliile de Halloween și mecanismul vizibil transformă această cutiuță într-un cadou aparte și într-un decor memorabil.' ELSE description END, story=CASE WHEN version=1 THEN 'Potrivită pentru cadouri, colecționari, petreceri și evenimente tematice, decoruri de Halloween sau adolescenți 12+. Funcționează mecanic, prin rotirea manivelei, fără baterii. Mică la dimensiuni. Mare la atmosferă. Imaginile sunt orientative și pot include elemente decorative care nu fac parte din produs.' ELSE story END WHERE slug='halloween';
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_halloween_0',id,'image','/produse/halloween/card.webp','Cutiuță Muzicală Halloween cu Manivelă – Cadou Misterios & Decor Tematic','image/webp','Cutiuță Muzicală Halloween cu Manivelă – Cadou Misterios & Decor Tematic','product','active','cleared',1,1,-100,0 FROM products WHERE slug='halloween' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_halloween_1',id,'image','/produse/halloween/1.webp','Capacul ilustrat, între dovleci','image/webp','Capacul ilustrat, între dovleci','product','active','cleared',1,1,-99,0 FROM products WHERE slug='halloween' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_halloween_2',id,'image','/produse/halloween/2.webp','Atmosferă de noapte de Halloween','image/webp','Atmosferă de noapte de Halloween','product','active','cleared',1,1,-98,0 FROM products WHERE slug='halloween' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_halloween_3',id,'image','/produse/halloween/3.webp','Mecanismul în detaliu','image/webp','Mecanismul în detaliu','product','active','cleared',1,1,-97,0 FROM products WHERE slug='halloween' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_halloween_4',id,'image','/produse/halloween/4.webp','Dimensiuni produs','image/webp','Dimensiuni produs','product','active','cleared',1,1,-96,0 FROM products WHERE slug='halloween' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_halloween_5',id,'image','/produse/halloween/5.webp','Cadoul care vrăjește','image/webp','Cadoul care vrăjește','product','active','cleared',1,1,-95,0 FROM products WHERE slug='halloween' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_halloween_6',id,'image','/produse/halloween/6.webp','Pornește magia de Halloween','image/webp','Pornește magia de Halloween','product','active','cleared',1,1,-94,0 FROM products WHERE slug='halloween' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_halloween_7',id,'image','/produse/halloween/7.webp','Mică cutie, vrajă mare','image/webp','Mică cutie, vrajă mare','product','active','cleared',1,1,-93,0 FROM products WHERE slug='halloween' AND version=1;

-- One-time editorial import. Existing administrator edits (version > 1) win.
UPDATE products SET short_name='You Are My Sunshine', landing_collection='emotion', landing_order=4, storefront_state='available', is_featured=0, details_json='["Melodie: You Are My Sunshine","Dimensiuni: aprox. 6,5 × 3,8 × 5 cm / 2.55 × 1.5 × 1.97 in","Lemn închis la culoare, ornamente decorative și mecanism metalic vizibil","Obiect de colecție 14+; nu este jucărie"]',
name=CASE WHEN version=1 THEN 'Cutiuță Muzicală „You Are My Sunshine” cu Manivelă – Cadou de Colecție 14+' ELSE name END, tagline=CASE WHEN version=1 THEN 'Uneori, cele mai frumoase amintiri încap într-o cutiuță.' ELSE tagline END, description=CASE WHEN version=1 THEN 'Cutiuța muzicală „You Are My Sunshine” este un mic obiect de colecție creat pentru a transforma un gest simplu într-un moment special. Designul din lemn, detaliile decorative și mesajul ascuns sub capac o fac potrivită atât pentru cupluri și familie, cât și pentru cei care iubesc obiectele cu poveste. Rotești ușor manivela metalică, cilindrul mecanismului pune în mișcare pieptenele muzical, iar melodia începe să se audă — fără baterii și fără încărcare.' ELSE description END, story=CASE WHEN version=1 THEN 'Mecanismul rămâne vizibil atunci când capacul este deschis, ceea ce îi oferă un farmec aparte și o transformă într-un obiect interesant de păstrat și expus. Este o alegere potrivită pentru aniversări, zile de naștere, Valentine’s Day, Crăciun, cadouri pentru partener, părinți sau persoane apropiate, dar și ca decor pentru birou, bibliotecă, vitrină, dormitor sau o colecție personală. Mică la dimensiuni, dar făcută să păstreze momente mari. Imaginile de prezentare sunt orientative; decorurile și accesoriile din fotografii nu sunt incluse.' ELSE story END WHERE slug='sunshine';
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_sunshine_0',id,'image','/produse/sunshine/card.webp','Cutiuță Muzicală „You Are My Sunshine” cu Manivelă – Cadou de Colecție 14+','image/webp','Cutiuță Muzicală „You Are My Sunshine” cu Manivelă – Cadou de Colecție 14+','product','active','cleared',1,1,-100,0 FROM products WHERE slug='sunshine' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_sunshine_1',id,'image','/produse/sunshine/1.webp','Un dar care cântă iubirea','image/webp','Un dar care cântă iubirea','product','active','cleared',1,1,-99,0 FROM products WHERE slug='sunshine' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_sunshine_2',id,'image','/produse/sunshine/2.webp','O amintire care rămâne','image/webp','O amintire care rămâne','product','active','cleared',1,1,-98,0 FROM products WHERE slug='sunshine' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_sunshine_3',id,'image','/produse/sunshine/3.webp','Cutiuța închisă, cu decor gravat','image/webp','Cutiuța închisă, cu decor gravat','product','active','cleared',1,1,-97,0 FROM products WHERE slug='sunshine' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_sunshine_4',id,'image','/produse/sunshine/4.webp','Dimensiuni produs','image/webp','Dimensiuni produs','product','active','cleared',1,1,-96,0 FROM products WHERE slug='sunshine' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_sunshine_5',id,'image','/produse/sunshine/5.webp','Farmec clasic, fără baterii','image/webp','Farmec clasic, fără baterii','product','active','cleared',1,1,-95,0 FROM products WHERE slug='sunshine' AND version=1;
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_sunshine_6',id,'image','/produse/sunshine/6.webp','Melodia You Are My Sunshine','image/webp','Melodia You Are My Sunshine','product','active','cleared',1,1,-94,0 FROM products WHERE slug='sunshine' AND version=1;

-- One-time editorial import. Existing administrator edits (version > 1) win.
UPDATE products SET short_name='Stăpânul Inelelor — One Ring', landing_collection='story', landing_order=5, storefront_state='coming_soon', is_featured=0, details_json='["Cutiuță din lemn cu decor ornamental","Mecanism manual cu manivelă","Cutie din lemn cu mecanism metalic vizibil"]',
name=CASE WHEN version=1 THEN 'Stăpânul Inelelor — One Ring' ELSE name END, tagline=CASE WHEN version=1 THEN 'Un dar pentru cei care știu ce înseamnă prețioasa comoară.' ELSE tagline END, description=CASE WHEN version=1 THEN 'O cutiuță care arată ca un mic artefact de colecție. Imaginea Inelului îl cucerește instant pe fanul Tolkien, iar lemnul cald îi dă acel aer de obiect păstrat cu grijă ani întregi. Este genul de cadou care impresionează un colecționar, un pasionat de fantasy sau pe cineva care încă retrăiește scenele din trilogie.' ELSE description END, story=CASE WHEN version=1 THEN 'Modelul One Ring are un impact imediat: foc, aur și simbolul cel mai recognoscibil din universul Stăpânul Inelelor. Pe pagina produsului am păstrat fotografia originală și am extras trei perspective din aceeași imagine ca să se vadă mai clar capacul, zona laterală și partea mecanică. Astfel, produsul rămâne autentic, dar este mai ușor de inspectat înainte de comandă.' ELSE story END WHERE slug='lotr-rings';
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_lotr-rings_0',id,'image','/produse/archive/lotr-rings.webp','Stăpânul Inelelor — One Ring','image/webp','Stăpânul Inelelor — One Ring','product','active','cleared',1,1,-100,0 FROM products WHERE slug='lotr-rings' AND version=1;

-- One-time editorial import. Existing administrator edits (version > 1) win.
UPDATE products SET short_name='Harry Potter — I Solemnly Swear', landing_collection='story', landing_order=6, storefront_state='coming_soon', is_featured=0, details_json='["Finisaj albastru intens, accente aurii","Mecanism manual cu manivelă","Potrivită pentru un cadou tematic","Mecanism clasic cu manivelă"]',
name=CASE WHEN version=1 THEN 'Harry Potter — I Solemnly Swear' ELSE name END, tagline=CASE WHEN version=1 THEN 'Pentru Potterhead-ul care zâmbește din prima la Harta Hoinarului.' ELSE tagline END, description=CASE WHEN version=1 THEN 'Nu este doar o cutiuță muzicală, ci un mic obiect care trimite direct la magia Hogwarts. Albastrul profund, scrisul auriu și tema vizuală o fac un cadou perfect pentru fanele și fanii Harry Potter care iubesc detaliile speciale, colecțiile tematice și obiectele cu personalitate. Este potrivită pentru aniversări, sărbători sau pentru acel cadou memorabil oferit fără o ocazie anume.' ELSE description END, story=CASE WHEN version=1 THEN 'Mesajul «I Solemnly Swear...» este recognoscibil dintr-o clipă pentru orice fan adevărat. Fotografia originală arată clar textura lemnului vopsit și poziția capacului, iar în galerie am evidențiat din aceeași imagine atât designul de pe capac, cât și zona mecanismului, pe cât permite cadrul real al pozei.' ELSE story END WHERE slug='hp-always';
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_hp-always_0',id,'image','/produse/archive/hp-always.webp','Harry Potter — I Solemnly Swear','image/webp','Harry Potter — I Solemnly Swear','product','active','cleared',1,1,-100,0 FROM products WHERE slug='hp-always' AND version=1;

-- One-time editorial import. Existing administrator edits (version > 1) win.
UPDATE products SET short_name='Zâna Pădurii Fermecate', landing_collection='story', landing_order=7, storefront_state='coming_soon', is_featured=0, details_json='["Capac ilustrat cu tematică fantasy","Cutie din lemn cu decor gravat","Mecanism vizibil parțial în fotografia originală","Cadou potrivit pentru aniversare sau Crăciun"]',
name=CASE WHEN version=1 THEN 'Zâna Pădurii Fermecate' ELSE name END, tagline=CASE WHEN version=1 THEN 'Un cadou delicat pentru visătoare și iubitoare de magie.' ELSE tagline END, description=CASE WHEN version=1 THEN 'Dacă vrei un cadou care să pară tandru, luminos și memorabil din prima clipă, modelul cu zână este alegerea potrivită. Îi va impresiona pe cei care iubesc poveștile fantasy, universurile delicate, cadourile poetice și obiectele care par desprinse dintr-o lume fermecată. Este potrivit atât pentru adolescente, cât și pentru femei care încă păstrează ceva visător în ele.' ELSE description END, story=CASE WHEN version=1 THEN 'Capacul ilustrat are un efect aproape cinematografic, iar cutiuța din lemn păstrează acel contrast frumos dintre materialul natural și imaginea luminoasă. În galerie am folosit numai fotografia originală, din care am evidențiat separat capacul și zona interioară, astfel încât produsul să rămână fidel realității.' ELSE story END WHERE slug='fairy';
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_fairy_0',id,'image','/produse/archive/fairy.webp','Zâna Pădurii Fermecate','image/webp','Zâna Pădurii Fermecate','product','active','cleared',1,1,-100,0 FROM products WHERE slug='fairy' AND version=1;

-- One-time editorial import. Existing administrator edits (version > 1) win.
UPDATE products SET short_name='Pirații Caraibilor — Furtuna', landing_collection='story', landing_order=8, storefront_state='coming_soon', is_featured=0, details_json='["Ilustrație marină dramatică","Cutiuță din lemn cu ornament","Mecanism cu manivelă laterală","Ilustrație tematică pe capac"]',
name=CASE WHEN version=1 THEN 'Pirații Caraibilor — Furtuna' ELSE name END, tagline=CASE WHEN version=1 THEN 'Pentru cei care aleg mereu aventura, nu varianta cuminte.' ELSE tagline END, description=CASE WHEN version=1 THEN 'Este unul dintre modelele cu cel mai mult dramatism vizual. Corabia din furtună și tonurile intense îl fac cadoul ideal pentru un fan al aventurii, al filmelor Pirates of the Caribbean sau pentru cineva care iubește obiectele decorative cu impact. Arată excelent ca surpriză pentru un iubitor de povești maritime, filme epice sau colecții tematice.' ELSE description END, story=CASE WHEN version=1 THEN 'Imaginea de pe capac transmite mișcare și tensiune, iar baza din lemn o echilibrează perfect. Pentru prezentarea produsului am păstrat cadrul original și am extras trei moduri de vizualizare din aceeași fotografie, ca să se vadă mai clar cutiuța, textura lemnului și partea mecanică.' ELSE story END WHERE slug='pirates';
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_pirates_0',id,'image','/produse/archive/pirates.webp','Pirații Caraibilor — Furtuna','image/webp','Pirații Caraibilor — Furtuna','product','active','cleared',1,1,-100,0 FROM products WHERE slug='pirates' AND version=1;

-- One-time editorial import. Existing administrator edits (version > 1) win.
UPDATE products SET short_name='Star Wars — Best Dad in the Galaxy', landing_collection='dedicated', landing_order=9, storefront_state='coming_soon', is_featured=0, details_json='["Mesaj pentru un cadou dedicat","Cutie din lemn cu finisaj închis","Mecanism manual cu manivelă","Fotografia modelului disponibil"]',
name=CASE WHEN version=1 THEN 'Star Wars — Best Dad in the Galaxy' ELSE name END, tagline=CASE WHEN version=1 THEN 'Genul de cadou care îl face pe tata să zâmbească imediat.' ELSE tagline END, description=CASE WHEN version=1 THEN 'Pentru un tată pasionat de Star Wars, modelul acesta merge direct la țintă. Mesajul este clar, amuzant și potrivit ca idee de cadou pentru ziua lui, Crăciun, Ziua Tatălui sau pur și simplu ca gest memorabil. Este genul de obiect mic, dar cu mare efect emoțional, mai ales pentru cineva care iubește universul galactic și cadourile tematice.' ELSE description END, story=CASE WHEN version=1 THEN 'Textul de pe capac face produsul imediat recognoscibil, iar lemnul închis îi dă un aer matur și elegant. În loc să schimbăm cutiuța, am ales să păstrăm exact fotografia originală și să construim o galerie de detaliu din ea, pentru un plus de claritate și încredere la comandă.' ELSE story END WHERE slug='starwars-dad';
INSERT INTO product_media(id,product_id,media_type,source_url,alt_text,mime_type,title,usage_type,status,rights_status,marketing_approved,public_access,sort_order,is_primary) SELECT 'editorial_starwars-dad_0',id,'image','/produse/archive/starwars-dad.webp','Star Wars — Best Dad in the Galaxy','image/webp','Star Wars — Best Dad in the Galaxy','product','active','cleared',1,1,-100,0 FROM products WHERE slug='starwars-dad' AND version=1;

UPDATE schema_metadata SET value='19' WHERE key='schema_version';
