/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComandaRouteImport } from './routes/comanda'
import { Route as FavoriteRouteImport } from './routes/favorite'
import { Route as GhidCadouriPersonalizateRouteImport } from './routes/ghid-cadouri-personalizate'
import { Route as PoliticaDeConfidentialitateRouteImport } from './routes/politica-de-confidentialitate'
import { Route as PovesteRouteImport } from './routes/poveste'
import { Route as ProduseRouteImport } from './routes/produse'
import { Route as ReturRouteImport } from './routes/retur'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermeniDeUtilizareRouteImport } from './routes/termeni-de-utilizare'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as ProdusIdRouteImport } from './routes/produs.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin/ai'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin/billing'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminEmailRouteImport } from './routes/_authenticated/admin/email'
import { Route as AuthenticatedAdminFinanciarRouteImport } from './routes/_authenticated/admin/financiar'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin/integrations'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin/inventory'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin/newsletter'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminPlatformsRouteImport } from './routes/_authenticated/admin/platforms'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin/posts'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminPromotionsRouteImport } from './routes/_authenticated/admin/promotions'
import { Route as AuthenticatedAdminQrGeneratorRouteImport } from './routes/_authenticated/admin/qr-generator'
import { Route as AuthenticatedAdminReturnsRouteImport } from './routes/_authenticated/admin/returns'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminShippingRouteImport } from './routes/_authenticated/admin/shipping'
import { Route as AuthenticatedAdminStatisticsRouteImport } from './routes/_authenticated/admin/statistics'
import { Route as AuthenticatedAdminSuppliersRouteImport } from './routes/_authenticated/admin/suppliers'
import { Route as AuthenticatedAdminTrafficRouteImport } from './routes/_authenticated/admin/traffic'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin/products.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandaRoute = ComandaRouteImport.update({
  id: '/comanda',
  path: '/comanda',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteRoute = FavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const GhidCadouriPersonalizateRoute =
  GhidCadouriPersonalizateRouteImport.update({
    id: '/ghid-cadouri-personalizate',
    path: '/ghid-cadouri-personalizate',
    getParentRoute: () => rootRouteImport,
  } as any)
const PoliticaDeConfidentialitateRoute =
  PoliticaDeConfidentialitateRouteImport.update({
    id: '/politica-de-confidentialitate',
    path: '/politica-de-confidentialitate',
    getParentRoute: () => rootRouteImport,
  } as any)
const PovesteRoute = PovesteRouteImport.update({
  id: '/poveste',
  path: '/poveste',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduseRoute = ProduseRouteImport.update({
  id: '/produse',
  path: '/produse',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturRoute = ReturRouteImport.update({
  id: '/retur',
  path: '/retur',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniDeUtilizareRoute = TermeniDeUtilizareRouteImport.update({
  id: '/termeni-de-utilizare',
  path: '/termeni-de-utilizare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProdusIdRoute = ProdusIdRouteImport.update({
  id: '/produs/$id',
  path: '/produs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailRoute = AuthenticatedAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFinanciarRoute =
  AuthenticatedAdminFinanciarRouteImport.update({
    id: '/financiar',
    path: '/financiar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPlatformsRoute =
  AuthenticatedAdminPlatformsRouteImport.update({
    id: '/platforms',
    path: '/platforms',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPromotionsRoute =
  AuthenticatedAdminPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQrGeneratorRoute =
  AuthenticatedAdminQrGeneratorRouteImport.update({
    id: '/qr-generator',
    path: '/qr-generator',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReturnsRoute =
  AuthenticatedAdminReturnsRouteImport.update({
    id: '/returns',
    path: '/returns',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminShippingRoute =
  AuthenticatedAdminShippingRouteImport.update({
    id: '/shipping',
    path: '/shipping',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStatisticsRoute =
  AuthenticatedAdminStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSuppliersRoute =
  AuthenticatedAdminSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTrafficRoute =
  AuthenticatedAdminTrafficRouteImport.update({
    id: '/traffic',
    path: '/traffic',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comanda': typeof ComandaRoute
  '/favorite': typeof FavoriteRoute
  '/ghid-cadouri-personalizate': typeof GhidCadouriPersonalizateRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/poveste': typeof PovesteRoute
  '/produse': typeof ProduseRoute
  '/retur': typeof ReturRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-de-utilizare': typeof TermeniDeUtilizareRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/produs/$id': typeof ProdusIdRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/financiar': typeof AuthenticatedAdminFinanciarRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/qr-generator': typeof AuthenticatedAdminQrGeneratorRoute
  '/admin/returns': typeof AuthenticatedAdminReturnsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/admin/statistics': typeof AuthenticatedAdminStatisticsRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comanda': typeof ComandaRoute
  '/favorite': typeof FavoriteRoute
  '/ghid-cadouri-personalizate': typeof GhidCadouriPersonalizateRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/poveste': typeof PovesteRoute
  '/produse': typeof ProduseRoute
  '/retur': typeof ReturRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-de-utilizare': typeof TermeniDeUtilizareRoute
  '/produs/$id': typeof ProdusIdRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/financiar': typeof AuthenticatedAdminFinanciarRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/admin/qr-generator': typeof AuthenticatedAdminQrGeneratorRoute
  '/admin/returns': typeof AuthenticatedAdminReturnsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/admin/statistics': typeof AuthenticatedAdminStatisticsRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/comanda': typeof ComandaRoute
  '/favorite': typeof FavoriteRoute
  '/ghid-cadouri-personalizate': typeof GhidCadouriPersonalizateRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/poveste': typeof PovesteRoute
  '/produse': typeof ProduseRoute
  '/retur': typeof ReturRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termeni-de-utilizare': typeof TermeniDeUtilizareRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/produs/$id': typeof ProdusIdRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/email': typeof AuthenticatedAdminEmailRoute
  '/_authenticated/admin/financiar': typeof AuthenticatedAdminFinanciarRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/platforms': typeof AuthenticatedAdminPlatformsRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/_authenticated/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/_authenticated/admin/qr-generator': typeof AuthenticatedAdminQrGeneratorRoute
  '/_authenticated/admin/returns': typeof AuthenticatedAdminReturnsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/_authenticated/admin/statistics': typeof AuthenticatedAdminStatisticsRoute
  '/_authenticated/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/_authenticated/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comanda'
    | '/favorite'
    | '/ghid-cadouri-personalizate'
    | '/politica-de-confidentialitate'
    | '/poveste'
    | '/produse'
    | '/retur'
    | '/sitemap.xml'
    | '/termeni-de-utilizare'
    | '/admin'
    | '/produs/$id'
    | '/admin/ai'
    | '/admin/billing'
    | '/admin/customers'
    | '/admin/email'
    | '/admin/financiar'
    | '/admin/integrations'
    | '/admin/inventory'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/platforms'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/qr-generator'
    | '/admin/returns'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/statistics'
    | '/admin/suppliers'
    | '/admin/traffic'
    | '/admin/'
    | '/admin/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comanda'
    | '/favorite'
    | '/ghid-cadouri-personalizate'
    | '/politica-de-confidentialitate'
    | '/poveste'
    | '/produse'
    | '/retur'
    | '/sitemap.xml'
    | '/termeni-de-utilizare'
    | '/produs/$id'
    | '/admin/ai'
    | '/admin/billing'
    | '/admin/customers'
    | '/admin/email'
    | '/admin/financiar'
    | '/admin/integrations'
    | '/admin/inventory'
    | '/admin/newsletter'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/platforms'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/qr-generator'
    | '/admin/returns'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/statistics'
    | '/admin/suppliers'
    | '/admin/traffic'
    | '/admin'
    | '/admin/products/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/comanda'
    | '/favorite'
    | '/ghid-cadouri-personalizate'
    | '/politica-de-confidentialitate'
    | '/poveste'
    | '/produse'
    | '/retur'
    | '/sitemap.xml'
    | '/termeni-de-utilizare'
    | '/_authenticated/admin'
    | '/produs/$id'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/email'
    | '/_authenticated/admin/financiar'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/platforms'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/promotions'
    | '/_authenticated/admin/qr-generator'
    | '/_authenticated/admin/returns'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/shipping'
    | '/_authenticated/admin/statistics'
    | '/_authenticated/admin/suppliers'
    | '/_authenticated/admin/traffic'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComandaRoute: typeof ComandaRoute
  FavoriteRoute: typeof FavoriteRoute
  GhidCadouriPersonalizateRoute: typeof GhidCadouriPersonalizateRoute
  PoliticaDeConfidentialitateRoute: typeof PoliticaDeConfidentialitateRoute
  PovesteRoute: typeof PovesteRoute
  ProduseRoute: typeof ProduseRoute
  ReturRoute: typeof ReturRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermeniDeUtilizareRoute: typeof TermeniDeUtilizareRoute
  ProdusIdRoute: typeof ProdusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comanda': {
      id: '/comanda'
      path: '/comanda'
      fullPath: '/comanda'
      preLoaderRoute: typeof ComandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite': {
      id: '/favorite'
      path: '/favorite'
      fullPath: '/favorite'
      preLoaderRoute: typeof FavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghid-cadouri-personalizate': {
      id: '/ghid-cadouri-personalizate'
      path: '/ghid-cadouri-personalizate'
      fullPath: '/ghid-cadouri-personalizate'
      preLoaderRoute: typeof GhidCadouriPersonalizateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-confidentialitate': {
      id: '/politica-de-confidentialitate'
      path: '/politica-de-confidentialitate'
      fullPath: '/politica-de-confidentialitate'
      preLoaderRoute: typeof PoliticaDeConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poveste': {
      id: '/poveste'
      path: '/poveste'
      fullPath: '/poveste'
      preLoaderRoute: typeof PovesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produse': {
      id: '/produse'
      path: '/produse'
      fullPath: '/produse'
      preLoaderRoute: typeof ProduseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retur': {
      id: '/retur'
      path: '/retur'
      fullPath: '/retur'
      preLoaderRoute: typeof ReturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni-de-utilizare': {
      id: '/termeni-de-utilizare'
      path: '/termeni-de-utilizare'
      fullPath: '/termeni-de-utilizare'
      preLoaderRoute: typeof TermeniDeUtilizareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/produs/$id': {
      id: '/produs/$id'
      path: '/produs/$id'
      fullPath: '/produs/$id'
      preLoaderRoute: typeof ProdusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email': {
      id: '/_authenticated/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AuthenticatedAdminEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financiar': {
      id: '/_authenticated/admin/financiar'
      path: '/financiar'
      fullPath: '/admin/financiar'
      preLoaderRoute: typeof AuthenticatedAdminFinanciarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/platforms': {
      id: '/_authenticated/admin/platforms'
      path: '/platforms'
      fullPath: '/admin/platforms'
      preLoaderRoute: typeof AuthenticatedAdminPlatformsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/promotions': {
      id: '/_authenticated/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AuthenticatedAdminPromotionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/qr-generator': {
      id: '/_authenticated/admin/qr-generator'
      path: '/qr-generator'
      fullPath: '/admin/qr-generator'
      preLoaderRoute: typeof AuthenticatedAdminQrGeneratorRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/returns': {
      id: '/_authenticated/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AuthenticatedAdminReturnsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/shipping': {
      id: '/_authenticated/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AuthenticatedAdminShippingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/statistics': {
      id: '/_authenticated/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AuthenticatedAdminStatisticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/suppliers': {
      id: '/_authenticated/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AuthenticatedAdminSuppliersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/traffic': {
      id: '/_authenticated/admin/traffic'
      path: '/traffic'
      fullPath: '/admin/traffic'
      preLoaderRoute: typeof AuthenticatedAdminTrafficRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
  }
}

interface AuthenticatedAdminProductsRouteChildren {
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
}

const AuthenticatedAdminProductsRouteChildren: AuthenticatedAdminProductsRouteChildren =
  {
    AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
  }

const AuthenticatedAdminProductsRouteWithChildren =
  AuthenticatedAdminProductsRoute._addFileChildren(
    AuthenticatedAdminProductsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminEmailRoute: typeof AuthenticatedAdminEmailRoute
  AuthenticatedAdminFinanciarRoute: typeof AuthenticatedAdminFinanciarRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminPlatformsRoute: typeof AuthenticatedAdminPlatformsRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRouteWithChildren
  AuthenticatedAdminPromotionsRoute: typeof AuthenticatedAdminPromotionsRoute
  AuthenticatedAdminQrGeneratorRoute: typeof AuthenticatedAdminQrGeneratorRoute
  AuthenticatedAdminReturnsRoute: typeof AuthenticatedAdminReturnsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminShippingRoute: typeof AuthenticatedAdminShippingRoute
  AuthenticatedAdminStatisticsRoute: typeof AuthenticatedAdminStatisticsRoute
  AuthenticatedAdminSuppliersRoute: typeof AuthenticatedAdminSuppliersRoute
  AuthenticatedAdminTrafficRoute: typeof AuthenticatedAdminTrafficRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
    AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
    AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
    AuthenticatedAdminEmailRoute: AuthenticatedAdminEmailRoute,
    AuthenticatedAdminFinanciarRoute: AuthenticatedAdminFinanciarRoute,
    AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
    AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
    AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminPlatformsRoute: AuthenticatedAdminPlatformsRoute,
    AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRoute,
    AuthenticatedAdminProductsRoute:
      AuthenticatedAdminProductsRouteWithChildren,
    AuthenticatedAdminPromotionsRoute: AuthenticatedAdminPromotionsRoute,
    AuthenticatedAdminQrGeneratorRoute: AuthenticatedAdminQrGeneratorRoute,
    AuthenticatedAdminReturnsRoute: AuthenticatedAdminReturnsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminShippingRoute: AuthenticatedAdminShippingRoute,
    AuthenticatedAdminStatisticsRoute: AuthenticatedAdminStatisticsRoute,
    AuthenticatedAdminSuppliersRoute: AuthenticatedAdminSuppliersRoute,
    AuthenticatedAdminTrafficRoute: AuthenticatedAdminTrafficRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComandaRoute: ComandaRoute,
  FavoriteRoute: FavoriteRoute,
  GhidCadouriPersonalizateRoute: GhidCadouriPersonalizateRoute,
  PoliticaDeConfidentialitateRoute: PoliticaDeConfidentialitateRoute,
  PovesteRoute: PovesteRoute,
  ProduseRoute: ProduseRoute,
  ReturRoute: ReturRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermeniDeUtilizareRoute: TermeniDeUtilizareRoute,
  ProdusIdRoute: ProdusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
